name: Build and lint
on:
  push:
    paths:
      - 'PKGBUILD'
      - '.github/workflows/lint.yml'
  workflow_dispatch:
jobs:
  linux-xanmod-tt:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v3
    - name: Build (LLVM)
      id: makepkg
      uses: CachyOS/pkgbuild-action@master
      with:
        pkgdir: "./"
        namcapExcludeRules: "invalidstartdir"
        makepkgArgs: "--skipchecksums --skippgpcheck --noconfirm -s"
    - uses: actions/upload-artifact@v3
      with:
        path: "./*.zst"
        
